// Fake main for operations .........................
// Fake main is used to JavaFx UI ...... 
public class FakeMain {
    public static void main(String[] args) {
        // Call the true main class...
        MyCal.Main.main(args);
    }

}
